AllCops:
  TargetRubyVersion: 2.4
  Include:
    - Gemfile
    - Guardfile
    - Rakefile
    - bin/*
    - features/**/*.rb
    - lib/**/*.rb
    - phut.gemspec
    - tasks/*.rake

Metrics/LineLength:
  Exclude:
    - features/step_definitions/*_steps.rb
    - test/**/*_test.rb

Metrics/MethodLength:
  Exclude:
    - test/**/*_test.rb

Metrics/AbcSize:
  Exclude:
    - test/**/*_test.rb

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/DotPosition:
  EnforcedStyle: trailing
