AllCops:
  TargetRubyVersion: 2.3
  Include:
    - Gemfile
    - Guardfile
    - Rakefile
    - bin/*
    - features/**/*.rb
    - lib/**/*.rb
    - phut.gemspec
    - spec/**/*.rb
    - tasks/*.rake

Metrics/LineLength:
  Exclude:
    - features/step_definitions/*_steps.rb
    - spec/**/*_spec.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ModuleLength:
  Exclude:
    - spec/**/*_spec.rb

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/DotPosition:
  EnforcedStyle: trailing
